openapi: '3.0.2'
info:
  title: Meteorological Administration API
  version: 1.0
tags:
 - name: kma

paths:
  /getUltraSrtNcst:
    get:
      tags:
        - kma
      summary: '초단기실황조회'
      description: "실황정보를 조회하기 위해 발표일자, 발표시각, 예보지점 X 좌표, 예보지점 Y 좌표의 조회 조건으로 자료구분코드, 실황값, 발표일자, 발표시각, 예보지점 X 좌표, 예보지점 Y 좌표의 정보를 조회하는 기능"
      operationId: getUltraSrtNcst
      parameters:
        - name: serviceKey
          in: query
          description: "인증키(URL Encode) - 공공데이터포털에서 발급받은 인증키 (size 100)"
          schema:
            type: string
          example: a8s7d9a8s7d...
        - name: numOfRows
          in: query
          description: "한 페이지 결과 수 - Default: 10 (size 4)"
          schema:
            type: string
          example: 10
        - name: pageNo
          in: query
          description: "페이지 번호 - Default: 1 (size 4)"
          schema:
            type: string
          example: 1
        - name: dataType
          in: query
          description: "요청자료형식(XML/JSON) - Default: XML (size 4)"
          schema:
            type: string
          example: JSON
        - name: base_date
          in: query
          description: "21년 6월 28일 발표 (size 8)"
          schema:
            type: string
          example: 20210628
        - name: base_time
          in: query
          description: "06시 발표(정시단위) - 매시각 10분 이후 호출 (size 4)"
          schema:
            type: string
          example: 0600
        - name: nx
          in: query
          description: "예보지점의 X 좌표값 (size 2)"
          schema:
            type: string
          example: 55
        - name: ny
          in: query
          description: "예보지점의 Y 좌표값 (size 2)"
          schema:
            type: string
          example: 127
      responses:
        '200':
          description: 응답 메시지 명세.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/resUltraSrtNcstVO'
components:
  schemas:
    resUltraSrtNcstVO:
      type: object
      properties:
        response:
          type: object
          properties:
            header:
              type: object
              properties:
                resultCode:
                  type: string
                  description: Result code of the API call.
                resultMsg:
                  type: string
                  description: Result message of the API call.
            body:
              type: object
              properties:
                dataType:
                  type: string
                  description: Data type of the response.
                items:
                  type: object
                  properties:
                    item:
                      type: array
                      items:
                        type: object
                        properties:
                          baseDate:
                            type: string
                            description: Base date of the observation.
                          baseTime:
                            type: string
                            description: Base time of the observation.
                          category:
                            type: string
                            description: Category of the observation data.
                            enum: 
                              - PTY
                              - REH
                              - RN1
                              - T1H
                              - UUU
                              - VEC
                              - VVV
                              - WSD
                          nx:
                            type: integer
                            description: X-coordinate of the grid.
                          ny:
                            type: integer
                            description: Y-coordinate of the grid.
                          obsrValue:
                            type: string
                            description: Observed value.
                pageNo:
                  type: integer
                  description: Page number of the response.
                numOfRows:
                  type: integer
                  description: Number of rows per page.
                totalCount:
                  type: integer
                  description: Total number of items.