openapi: '3.0.2'
info:
  title: kma API
  version: 1.0
tags:
 - name: kma

paths:
  /getUltraSrtNcst:
    get:
      tags:
        - kma-controller
      summary: '초단기실황조회'
      description: "실황정보를 조회하기 위해 발표일자, 발표시각, 예보지점 X 좌표, 예보지점 Y 좌표의 조회 조건으로 자료구분코드, 실황값, 발표일자, 발표시각, 예보지점 X 좌표, 예보지점 Y 좌표의 정보를 조회하는 기능"
      operationId: getUltraSrtNcst
      parameters:
        - name: lon
          in: query
          description: "경도"
          schema:
            type: string
          example: 126.92980
        - name: lat
          in: query
          description: "위도"
          schema:
            type: string
          example: 37.48819
      responses:
        '200':
          description: 응답 메시지 명세.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/resUltraSrtNcstVO'
components:
  schemas:
    resUltraSrtNcstVO:
      type: object
      properties:
        response:
          type: object
          properties:
            header:
              type: object
              properties:
                resultCode:
                  type: string
                  description: Result code of the API call.
                resultMsg:
                  type: string
                  description: Result message of the API call.
            body:
              type: object
              properties:
                dataType:
                  type: string
                  description: Data type of the response.
                items:
                  type: object
                  properties:
                    item:
                      type: array
                      items:
                        type: object
                        properties:
                          baseDate:
                            type: string
                            description: Base date of the observation.
                          baseTime:
                            type: string
                            description: Base time of the observation.
                          category:
                            type: string
                            description: Category of the observation data.
                            enum: 
                              - PTY
                              - REH
                              - RN1
                              - T1H
                              - UUU
                              - VEC
                              - VVV
                              - WSD
                          nx:
                            type: integer
                            description: X-coordinate of the grid.
                          ny:
                            type: integer
                            description: Y-coordinate of the grid.
                          obsrValue:
                            type: string
                            description: Observed value.
                pageNo:
                  type: integer
                  description: Page number of the response.
                numOfRows:
                  type: integer
                  description: Number of rows per page.
                totalCount:
                  type: integer
                  description: Total number of items.