openapi: '3.0.2'
info:
  title: kma API
  version: 1.0
tags:
 - name: kma

paths:
  /getUltraSrtNcst:
    get:
      tags:
        - kma-controller
      summary: '초단기실황조회'
      description: "실황정보를 조회하기 위해 발표일자, 발표시각, 예보지점 X 좌표, 예보지점 Y 좌표의 조회 조건으로 자료구분코드, 실황값, 발표일자, 발표시각, 예보지점 X 좌표, 예보지점 Y 좌표의 정보를 조회하는 기능"
      operationId: getUltraSrtNcst
      parameters:
        - name: lat
          in: query
          description: "위도"
          schema:
            type: string
          example: 37.48819
        - name: lon
          in: query
          description: "경도"
          schema:
            type: string
          example: 126.92980
      responses:
        '200':
          description: 응답 메시지 명세.
          content:
            application/json:
              schema:
                $ref: './kma/resUltraSrtNcstDTO.yml#/components/schemas/resUltraSrtNcstDTO'
