spring:
  config:
    import:
    - optional:classpath:/config/feignclient.yml
    - optional:classpath:/config/authkeys.yml
    - optional:classpath:/config/logging.yml
  application:
    name: board

server:
  port: 7000
  root-url: /

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true
    configUrl: /v3/api-docs/swagger-config
    url: /v3/api-docs
    tryItOutEnabled: true
  bearer:
    name: BearerAuth
    scheme: bearer
    bearerFormat: JWT
  info:
    title: "openapi Test"
    version: 1.0
    description: 'openapi dddddddescription'
  license:
    name: Apache License Version 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0
