spring:
  application:
    name: board

server:
  port: 7000

springdoc:
  api-docs:
    version: 'OPENAPI_3_0'
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true
    configUrl: /v3/api-docs/swagger-config
    url: /v3/api-docs